name: mulberrydev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - r-base=4.3.*
  - r-ape
  - r-biocmanager
  - r-tidytree
  - r-tidyverse
  - r-phytools
  - r-gplots
  - r-systemfonts
  - bioconductor-ggtree
  - bioconductor-treeio
  - fontconfig
  - freetype
  - pip
  - pip:
    - setuptools
